# Generated by Django 3.2.8 on 2021-10-20 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tag_line', models.CharField(max_length=200)),
                ('s_description', models.TextField()),
                ('l_description', models.TextField()),
                ('lang_used', models.TextField()),
                ('proj_image', models.ImageField(upload_to='images/')),
                ('release', models.DateTimeField(default=datetime.datetime(2021, 10, 20, 22, 15, 23, 690051))),
            ],
        ),
    ]
