# Generated by Django 3.2.8 on 2021-10-21 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211021_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 9, 3, 30, 467570)),
        ),
        migrations.AlterField(
            model_name='project',
            name='release',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 9, 3, 30, 467570)),
        ),
    ]
