# Generated by Django 3.2.8 on 2021-10-23 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211021_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 21, 52, 34, 469003)),
        ),
        migrations.AlterField(
            model_name='project',
            name='release',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 21, 52, 34, 469003)),
        ),
    ]
