# Generated by Django 3.2.8 on 2021-10-23 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211023_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 22, 7, 58, 95513)),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='release',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 22, 7, 58, 95513)),
        ),
    ]
