# Generated by Django 3.2.7 on 2021-11-22 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211122_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tag_line',
        ),
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 19, 30, 42, 844761)),
        ),
        migrations.AlterField(
            model_name='project',
            name='release',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 19, 30, 42, 843762)),
        ),
    ]
