# Generated by Django 3.2.8 on 2021-11-27 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211122_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_link_name',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 9, 58, 21, 636310)),
        ),
        migrations.AlterField(
            model_name='project',
            name='release',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 9, 58, 21, 636310)),
        ),
    ]
