# Generated by Django 3.2.8 on 2021-11-27 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211127_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 9, 59, 30, 388743)),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_link_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='release',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 9, 59, 30, 388743)),
        ),
    ]
