# Generated by Django 3.2.8 on 2021-11-27 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211127_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 13, 46, 27, 679578)),
        ),
        migrations.AlterField(
            model_name='project',
            name='release',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 13, 46, 27, 679578)),
        ),
    ]
