# Generated by Django 3.2.8 on 2021-11-27 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211127_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='activate',
            new_name='launch',
        ),
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 13, 53, 41, 363081)),
        ),
        migrations.AlterField(
            model_name='project',
            name='release',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 13, 53, 41, 363081)),
        ),
    ]
